name: Build
on:
  push:
    branches:
      - dev/*
jobs:
  Build:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk
    environment: main
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: dotnet build
      