name: Deploy with AWS CDK
on:
  push:
    branches:
      - main
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
jobs:
  Deploy:
    # container: python:3.10
    runs-on: ubuntu-latest
    environment: main
    steps:
      - uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::342755627552:role/IYarlesGithubActionsOidcRole
          role-session-name: DeployIYarlesRoleSession
          aws-region: us-east-2

      - uses: actions/setup-node@v3
        with:
          check-latest: true
      
      # Install AWS CDK class="pb-4"
      # - run: npm install -g typescript
      - run: npm install -g aws-cdk

      # Setup Python 3.10
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: python -m pip install --upgrade pip

      # Install requirements (aws cdk stuff)
      - run: pip install -r requirements.txt

      # Bootstrap CDK
      - run: cdk bootstrap
        env:
          AWS_DEFAULT_REGION: us-east-2

      # Deploy with CDK
      - run: cdk deploy --require-approval never
        env:
          AWS_DEFAULT_REGION: us-east-2
          GOOGLE_APP_PASSWORD: ${{ secrets.GOOGLE_APP_PASSWORD }}
          IYARLES_ReCaptcha__ScoreThreshold: ${{ secrets.IYARLES_ReCaptcha__ScoreThreshold }}
          IYARLES_ReCaptcha__SecretKey: ${{ secrets.IYARLES_ReCaptcha__SecretKey }}
          IYARLES_ReCaptcha__SiteKey: ${{ secrets.IYARLES_ReCaptcha__SiteKey }}
          IYARLES_ReCaptcha__UseRecaptchaNet: ${{ secrets.IYARLES_ReCaptcha__UseRecaptchaNet }}
          IYARLES_ReCaptcha__Version: ${{ secrets.IYARLES_ReCaptcha__Version }}
