name: Deploy with AWS CDK
on:
  push:
    branches:
      - main
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
jobs:
  Deploy:
    container: python:3.10
    runs-on: ubuntu-latest
    environment: main
    steps:
      - uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::342755627552:role/IYarlesGithubActionsOidcRole
          role-session-name: DeployIYarlesRoleSession
          aws-region: us-east-2

      - uses: actions/setup-node@v3
        with:
          check-latest: true
      
      # Install AWS CDK
      # - run: npm install -g typescript
      - run: npm install -g aws-cdk

      # Install requirements (aws cdk stuff)
      - run: pip install -r requirements.txt

      # Deploy with CDK
      - run: cdk deploy --require-approval never
