name: Build & Deploy on Azure
on:
  push:
    branches:
      - main
jobs:
  my-job:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - uses: actions/checkout@v3
      - uses: azure/docker-login@v1
        with:
          login-server: 'yarles.azurecr.io' # default: index.docker.io
          username: ${{ secrets.AZR_USERNAME }}
          password: ${{ secrets.AZR_PASSWORD }}
      
      - name: Build
        run: docker build -t yarles.azurecr.io/iyarles:latest .
      
      - name: Deploy # Webhook on registry will deploy to App Service on push
        run: docker push yarles.azurecr.io/iyarles:latest